org.gradle.daemon=false
org.gradle.jvmargs=-Xms512M -Xmx1G -Dfile.encoding=UTF-8 -Dconsole.encoding=UTF-8
org.gradle.configureondemand=false

projectVersion=0.0.1

kotlinVersion=2.0.21
gdxVersion=1.12.1

aiVersion=1.8.2
gdxControllersVersion=2.2.3
controllerMappingVersion=2.3.0
ktxVersion=1.12.1-rc2

typingLabelVersion=1.4.0

jacksonVersion=2.16.1
assertjVersion=3.25.3
mockitoVersion=5.10.0
kockitoVersion=5.2.1
junitVersion=5.10.2

graalHelperVersion=2.0.1
enableGraalNative=false
