package nl.t64.cot.components.party.spells

import nl.t64.cot.components.party.SuperEnum

enum class SpellItemId : SuperEnum {

    NONE,

    // Elemental Spells
    AIR_SHIELD,
    CONTROL_ELEMENTAL,
    DEBILITATION,
    DRAGON_FLAMES,
    EARTH_SMITE,
    FIREBALL,
    IMMOLATION,
    LIGHTNING,
    REMOVE_POISON,
    STRENGTH,
    WIND,

    // Naming Spells
    BANISHING,
    BRILLIANCE,
    CHARMING,
    CONTROL_MARQUIS,
    ENDURANCE,
    SENSE_AURA,
    STUPIDITY,
    TELEPORTATION,
    WEAKNESS,

    // Necromancy Spells
    ACID_BOLT,
    AURA_OF_DEATH,
    CHEAT_DEATH,
    CONTROL_ZOMBIES,
    CRUSHING_DEATH,
    DARKNESS,
    EXHAUSTION,
    HASTE,
    SPIRIT_SHIELD,
    STAMINA,
    TAP_STAMINA,
    WALL_OF_BONES,
    WRAITH_TOUCH,

    // Neutral Spells
    DISPEL_ELEMENTAL,
    DISPEL_NAMING,
    DISPEL_NECROMANCY,
    DISPEL_STAR,
    MIRROR,
    VS_ELEMENTAL,
    VS_NAMING,
    VS_NECROMANCY,
    VS_STAR,

    // Star Spells
    CLUMSINESS,
    DEXTERITY,
    FROZEN_DOOM,
    LIGHT,
    PHOTOSYNTHESIS,
    SOLAR_WRATH,
    STARLIGHT_SHIELD,
    STELLAR_GRAVITY,
    WEB_OF_STARLIGHT,
    WHITEFIRE;

    override val title: String = name

    // todo, this list is generated by AI, not checked by my. this list and also title have to change to the new magic system.

}
