package nl.t64.cot.components.conversation


enum class ConversationCommand {
    EXIT,
    HERO_JOIN,
    HERO_DISMISS,
    LOAD_SHOP,
    LOAD_ACADEMY,
    LOAD_SCHOOL,
    SAVE_GAME,
    HEAL_LIFE,
    RECEIVE_XP,
    RECEIVE_SPELLS,
    RECEIVE_ITEMS,
    START_BATTLE,
    RELOAD_NPCS,

    KNOW_QUEST,
    ACCEPT_QUEST,
    TRADE_QUEST_ITEMS,
    SHOW_QUEST_ITEM,
    WEAR_QUEST_ITEM,
    GIVE_QUEST_ITEM,
    SAY_QUEST_THING,
    RECEIVE_QUEST_ITEM_TO_DELIVER,
    DELIVER_QUEST_ITEM,
    DELIVER_QUEST_ITEM_ALTERNATE,
    DELIVER_QUEST_MESSAGE,

    REWARD_QUEST,

    NONE,


    BONUS_REWARD_QUEST,
    FAIL_QUEST,

}
